export const siteConfig = {
  name: 'Tal Barahi Handicraft',
  tagline: 'Premium New Zealand Wool. Powering Nepal\'s Craft Heritage.',
  description: 'For over three decades, Tal Barahi Handicraft has been the trusted backbone of Nepal\'s carpet, felt, and textile industries — supplying premium New Zealand wool from Kathmandu with consistency, quality, and care.',
  address: 'Mulpani, Kathmandu, Nepal',
  phone: '+977 9851063891, +977 9851060473',
  email: 'info@talbarahihandicraft.com.np',
  established: '1994',
};

export const woolCategories = [
  {
    id: 1,
    name: 'Raw White Wool',
    category: 'Natural',
    description: 'Unprocessed, naturally white New Zealand sheep wool in its most pure form. Ideal as a base for any dyeing or processing application.',
    applications: ['Carpet Manufacturing', 'Felt Production', 'Raw Textile Input'],
    micron: '26–34 µm',
    color: '#F0EAE2',
    accent: '#C9B49A',
  },
  {
    id: 2,
    name: 'Natural Wool',
    category: 'Natural',
    description: 'Premium New Zealand wool retaining its natural character — lanolin-rich, resilient, and consistent in quality across every batch.',
    applications: ['Handmade Carpets', 'Artisan Weaving', 'Premium Felting'],
    micron: '28–32 µm',
    color: '#E8DDD0',
    accent: '#B8A48A',
  },
  {
    id: 3,
    name: 'Colored & Dyed Wool',
    category: 'Processed',
    description: 'AZO-free dyed wool in a broad spectrum of colours. Consistent, fade-resistant, and compliant with international export standards.',
    applications: ['Decorative Carpets', 'Felt Art', 'Handicraft Export'],
    micron: '26–30 µm',
    color: '#D4B5B5',
    accent: '#8B2C2C',
  },
  {
    id: 4,
    name: 'Carded Wool',
    category: 'Processed',
    description: 'Machine-carded for uniform fiber alignment and consistency. Ideal for felt production and industries requiring fluffy, open-structure wool.',
    applications: ['Industrial Felting', 'Needle Felting', 'Insulation'],
    micron: '28–36 µm',
    color: '#E0D5C8',
    accent: '#A8956E',
  },
  {
    id: 5,
    name: 'Uncarded Wool',
    category: 'Natural',
    description: 'Raw, unwashed locks in their natural staple form. Preferred by traditional artisans and hand-processors who want full control over preparation.',
    applications: ['Hand Spinning', 'Traditional Weaving', 'Artisan Studios'],
    micron: '28–34 µm',
    color: '#EDE6DB',
    accent: '#9A8870',
  },
  {
    id: 6,
    name: 'Carpet Wool',
    category: 'Industrial',
    description: 'Heavy, resilient wool specifically graded for carpet pile. High durability, excellent compression recovery, and long pile stability.',
    applications: ['Hand-Knotted Carpets', 'Tufted Rugs', 'Commercial Flooring'],
    micron: '30–38 µm',
    color: '#D8C9B8',
    accent: '#7A6848',
  },
  {
    id: 7,
    name: 'Felting Wool',
    category: 'Industrial',
    description: 'Specially selected for its natural felting properties. Creates dense, durable felt sheets with consistent thickness and smooth surface.',
    applications: ['Industrial Felt', 'Needle Felting', 'Wet Felting'],
    micron: '26–30 µm',
    color: '#DDD0C8',
    accent: '#9B7E6B',
  },
  {
    id: 8,
    name: 'Fine Micron Wool',
    category: 'Premium',
    description: 'Fine-grade New Zealand wool for premium applications. Soft, lustrous, and refined — the choice for high-end knitting and luxury textile production.',
    applications: ['Fine Knitting', 'Premium Textiles', 'Luxury Garments'],
    micron: '18–24 µm',
    color: '#E8E0D5',
    accent: '#6B5A4A',
  },
  {
    id: 9,
    name: 'Knitting Yarn Wool',
    category: 'Processed',
    description: 'Spun and prepared specifically for the knitting industry. Available in various ply weights and consistent twist for machine and hand knitting.',
    applications: ['Machine Knitting', 'Hand Knitting', 'Knitwear Production'],
    micron: '22–28 µm',
    color: '#E0D8D0',
    accent: '#8A7A6A',
  },
  {
    id: 10,
    name: 'Industrial Bulk Supply',
    category: 'Industrial',
    description: 'Large-volume wool supply for manufacturers, exporters, and industrial buyers. Consistent grade, competitive pricing, and reliable scheduling.',
    applications: ['Large-Scale Manufacturing', 'Export Processing', 'Industrial Textile'],
    micron: 'Various grades',
    color: '#D5CFC9',
    accent: '#7A7068',
  },
];

export const industries = [
  {
    id: 1,
    name: 'Carpet Manufacturing',
    icon: '⟡',
    description: 'Nepal\'s world-famous hand-knotted carpets have long relied on high-quality wool as their foundation. Tal Barahi has been a consistent supply partner for leading Nepalese carpet manufacturers for over two decades.',
    detail: 'From fine Tibetan knot to traditional Dhurrie, our carpet-grade wool provides the resilience, pile height consistency, and dye uptake that carpet producers demand.',
    stat: '30+ years',
    statLabel: 'Supplying carpet industry',
  },
  {
    id: 2,
    name: 'Felt Manufacturing',
    icon: '◈',
    description: 'The Nepalese felt industry produces both artistic and industrial felt products exported globally. Our specially selected felting wool offers optimal fiber scales for consistent, durable felt formation.',
    detail: 'Whether wet felting, needle felting, or industrial felt sheet production — our wool provides the natural felting properties that synthetic alternatives cannot replicate.',
    stat: 'Industrial Grade',
    statLabel: 'Felting wool quality',
  },
  {
    id: 3,
    name: 'Knitting Industry',
    icon: '◎',
    description: 'Nepal\'s knitting sector produces garments, accessories, and home textiles for global export. We supply fine and medium-grade wool suited for both machine and hand knitting applications.',
    detail: 'Consistent micron grading and preparation standards ensure predictable results for knitwear manufacturers working to international quality specifications.',
    stat: 'Fine to Bulky',
    statLabel: 'Weight range available',
  },
  {
    id: 4,
    name: 'Textile Manufacturing',
    icon: '◇',
    description: 'Wool fabric weavers and textile manufacturers across Nepal rely on us for consistent raw material supply. Our wool is graded for textile processing including weaving, spinning, and finishing.',
    detail: 'From traditional Dhaka weaving to modern automated looms — we understand the different wool specifications each textile process requires.',
    stat: 'All Grades',
    statLabel: 'Textile wool supply',
  },
  {
    id: 5,
    name: 'Handicraft Producers',
    icon: '✦',
    description: 'Nepal\'s handicraft sector — from small artisan studios to medium export houses — depends on reliable, quality wool supply. We serve producers of all scales with consistent material.',
    detail: 'Our flexible supply model accommodates small batch orders for artisan studios alongside large-volume requirements for handicraft exporters.',
    stat: 'All Scales',
    statLabel: 'From artisan to exporter',
  },
  {
    id: 6,
    name: 'Wool Artisans',
    icon: '◉',
    description: 'Individual wool artisans — felters, weavers, dyers, and fiber artists — are among the craftspeople we have served across Nepal. We respect the artisan tradition as the heart of our industry.',
    detail: 'We provide natural, undyed, and hand-dyed wool for artisans who value authenticity of material as much as technique.',
    stat: 'Est. 1994',
    statLabel: 'Supporting artisans since',
  },
  {
    id: 7,
    name: 'Export Houses',
    icon: '◑',
    description: 'Nepalese export houses shipping carpet, felt, and textile products globally depend on traceable, internationally compliant wool. Our certified supply chain meets international buyer standards.',
    detail: 'Full documentation including country of origin (New Zealand), IWTO certification, and AZO-free dye compliance supports export requirements across markets.',
    stat: 'IWTO + SGS',
    statLabel: 'Certified quality supply',
  },
];

export const certifications = [
  {
    id: 1,
    name: '100% New Zealand Wool',
    description: 'All wool is sourced exclusively from New Zealand farms — the global standard for premium sheep wool quality and animal welfare.',
    icon: 'NZ',
  },
  {
    id: 2,
    name: 'SGS Tested',
    description: 'Independent SGS laboratory testing verifies the quality, composition, and safety of our wool consignments before import.',
    icon: 'SGS',
  },
  {
    id: 3,
    name: 'IWTO Certified',
    description: 'Compliance with International Wool Textile Organisation standards — the international benchmark for wool product quality and labelling.',
    icon: 'IWTO',
  },
  {
    id: 4,
    name: 'Mulesing-Free',
    description: 'All wool is sourced from mulesing-free sheep farming operations, meeting international animal welfare standards demanded by premium buyers.',
    icon: 'MF',
  },
  {
    id: 5,
    name: 'AZO-Free Dyes',
    description: 'Our dyed wool uses only AZO-free, non-toxic dye formulations — safe for artisans, compliant with EU and global export standards.',
    icon: 'AZO',
  },
  {
    id: 6,
    name: 'Fire Safe',
    description: 'Wool\'s natural fire resistance properties are maintained throughout our supply chain — important for carpet and textile safety compliance.',
    icon: 'FS',
  },
];

export const directors = [
  {
    id: 1,
    name: 'Bishnu Mani Lohani',
    title: 'Founder and Director',
    photo: '/images/team/Bishnu Mani Lohani.png',
    tagline: 'Building trusted relationships since 1994.',
    bio: 'A founding visionary of Tal Barahi Handicraft, bringing decades of expertise in the Nepalese textile industry and establishing the company\'s foundation in premium wool sourcing.',
  },
  {
    id: 2,
    name: 'Khet Raj Pathak',
    title: 'Founder and Director',
    photo: '/images/team/Khet Raj Pathak.png',
    tagline: 'Three Decades in Wool Logistics & Quality.',
    bio: 'A specialist in import logistics and wool grading, he has spent three decades building the supply chain infrastructure that ensures consistent, reliable delivery of New Zealand wool to Nepalese industries.',
  },
  {
    id: 3,
    name: 'Ram Hari Panta',
    title: 'Founder and Director',
    photo: '/images/team/Ram Hari Panta.png',
    tagline: 'Strengthening Nepal\'s Supply Network.',
    bio: 'His deep understanding of Nepal\'s handicraft export ecosystem has been central to positioning Tal Barahi as a trusted supplier for the country\'s most demanding carpet and textile manufacturers.',
  },
  {
    id: 4,
    name: 'Som Raj Pandey',
    title: 'Founder and Director',
    photo: '/images/team/Som Raj Pandey.png',
    tagline: 'Preserving generations of wool processing knowledge and craftsmanship.',
    bio: 'With roots in Nepal\'s wool dyeing tradition, he guided the company\'s early years through hands-on knowledge of fiber processing, quality grading, and industry relationships across the Kathmandu valley.',
  },
];

export const timeline = [
  {
    year: 'Early 1990s',
    title: 'A Humble Beginning',
    description: 'Four partners came together in Kathmandu with a shared entrepreneurial vision — rooted in Nepal\'s textile tradition and a belief in quality materials.',
  },
  {
    year: 'Mid 1990s',
    title: 'Wool Dyeing Era',
    description: 'The company established itself in wool dyeing and related industries including Pashmina and early textile work — building deep knowledge of fiber and craft.',
  },
  {
    year: 'Late 1990s',
    title: 'Growing Relationships',
    description: 'Gradual expansion of the supply network across Nepal\'s carpet and handicraft sectors. Trust became the company\'s most valuable asset.',
  },
  {
    year: 'Early 2000s',
    title: 'New Zealand Partnership',
    description: 'A defining turning point — Tal Barahi began importing premium sheep wool directly from New Zealand, opening a new chapter in quality and consistency.',
  },
  {
    year: '2010s',
    title: 'Industry Backbone',
    description: 'Three decades in, Tal Barahi became a recognized backbone of Nepal\'s wool supply ecosystem — trusted by carpet makers, felters, knitters, and exporters across the country.',
  },
  {
    year: 'Today',
    title: 'Three Decades of Trust',
    description: 'Still family-guided, still relationship-driven. Tal Barahi continues its mission — premium New Zealand wool, consistently supplied, supporting Nepal\'s craftsmanship industry for generations.',
  },
];

export const galleryItems = [
  { id: 1, label: 'New Zealand Pastoral', size: 'tall', bg: '#4A6741', text: '#FDF9F7' },
  { id: 2, label: 'Raw Wool Fiber', size: 'wide', bg: '#C9B49A', text: '#2B2B29' },
  { id: 3, label: 'Carpet Artisan', size: 'square', bg: '#8B2C2C', text: '#FDF9F7' },
  { id: 4, label: 'Wool Processing', size: 'square', bg: '#3D3D3A', text: '#E0D5D0' },
  { id: 5, label: 'NZ Sheep Flock', size: 'tall', bg: '#6B7D5E', text: '#FDF9F7' },
  { id: 6, label: 'Colored Wool Range', size: 'wide', bg: '#B8A48A', text: '#2B2B29' },
  { id: 7, label: 'Kathmandu Warehouse', size: 'square', bg: '#5A4A3A', text: '#FDF9F7' },
  { id: 8, label: 'Felting Craft', size: 'square', bg: '#A83535', text: '#FDF9F7' },
  { id: 9, label: 'Highland Farm', size: 'wide', bg: '#7A9060', text: '#FDF9F7' },
  { id: 10, label: 'Dyeing Process', size: 'tall', bg: '#6B1F1F', text: '#E0D5D0' },
  { id: 11, label: 'Knitting Workshop', size: 'square', bg: '#4A3828', text: '#FDF9F7' },
  { id: 12, label: 'Export Packing', size: 'square', bg: '#2B2B29', text: '#E0D5D0' },
];

export const insights = [
  {
    id: 1,
    title: 'Understanding Micron Grades in Sheep Wool',
    excerpt: 'A guide to how micron measurement defines wool quality and suitability across carpet, felting, and textile applications.',
    category: 'Wool Knowledge',
    date: 'Coming Soon',
    readTime: '5 min read',
  },
  {
    id: 2,
    title: 'Nepal\'s Carpet Industry: A Global Heritage',
    excerpt: 'How Nepal became one of the world\'s most respected producers of hand-knotted carpets — and the wool supply chain behind it.',
    category: 'Industry',
    date: 'Coming Soon',
    readTime: '8 min read',
  },
  {
    id: 3,
    title: 'Why New Zealand Wool Sets the Global Standard',
    excerpt: 'Exploring the climatic, agricultural, and farming factors that make New Zealand wool consistently superior for industrial and artisan applications.',
    category: 'Sourcing',
    date: 'Coming Soon',
    readTime: '6 min read',
  },
  {
    id: 4,
    title: 'Mulesing-Free: What It Means and Why It Matters',
    excerpt: 'The growing importance of ethical wool sourcing in international trade, and how Tal Barahi ensures full compliance with animal welfare standards.',
    category: 'Quality',
    date: 'Coming Soon',
    readTime: '4 min read',
  },
  {
    id: 5,
    title: 'The Art of Felting: From Wool to Finished Product',
    excerpt: 'An inside look at Nepal\'s felt industry — the materials, techniques, and quality requirements that define world-class Nepalese felt.',
    category: 'Craft',
    date: 'Coming Soon',
    readTime: '7 min read',
  },
  {
    id: 6,
    title: 'Supply Chain Transparency in the Wool Trade',
    excerpt: 'How traceability from New Zealand farms to Kathmandu warehouses supports both quality assurance and international buyer confidence.',
    category: 'Supply Chain',
    date: 'Coming Soon',
    readTime: '5 min read',
  },
];
